### ISSUE TITLE
When will you load your code into github?

### ISSUE THREAD

**Issue by xuzhang5788** [Hanjun-Dai/sdvae#1]
I read your paper and want to apply your method to my own problems. Your method is much more superior than other VAE methods. I am looking forward to trying your code. Thank you very much.

**Comment by xuzhang5788** [comment]
Thank you Hanjun-Dai for loading your code into github. Could you please add more information about your code, such as how to use it, an ipython notebook example, what libraries are needed, and so on.

**Comment by Hanjun-Dai** [comment]
Hi there, please see my updated README, and let me know if there's any question.
