### ISSUE TITLE
If it possible to use teacher forcing to train the RNN decoder?

### ISSUE THREAD

**Issue by chaoyan1037** [Hanjun-Dai/sdvae#5]
Hi Haijun, thanks for sharing your code, it is great implementation.
As I go through your code, I found you did not adopt teacher forcing to train the RNN decoder. I would like to know, if it is possible to do that? The major difficulty is in the testing. To do that, we need to get the rule masks on the fly, that is to say, every time we generate a production rule, we need to know the current rule mask given the current state of production rules prefix. In your code, you have the whole production rules, then you can get the rule masks for each production rule.

I would like to listen to your opinion before diving into the implementation. Thanks.

**Comment by Hanjun-Dai** [comment]
Hi,

Sorry for the late reply. I think the main reason here is to make a non-autoregressive decoder. If the decoder is too powerful, then it can simply cover the distribution without conditioning on the encoding -- this is just my hypothesis, and I think it might still work, as there have been many autoregressive + VAE works.

**Comment by chaoyan1037** [comment]
Thanks for your reply. I have tried and it works well.
