### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by vthost** [Hanjun-Dai/sdvae#6]
Hi! 
Regarding the dependencies, do you need everything from grammarVAE (their requirements.txt, I don't think so because they use keras instead of pytorch) or is Section 2 only about Theano. If the latter is the case, could you please share the dependencies for this project?
Thank you for providing the code!

**Comment by Hanjun-Dai** [comment]
Hi,

Yes I guess we mainly need a specific version of Theano to run the bayesian optimization. 
You'll still need to follow the instruction from grammarVAE to install the dependency.
